<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Carbon;

class PermissionsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Permission::truncate();
        Permission::insert([
            [
                'id' => 1,
                'parent_id' => 0,
                'name' => 'dashboard',
                'description' => 'Dashboard',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'parent_id' => 1,
                'name' => 'dashboard-reports',
                'description' => 'Dashboard Reports',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'parent_id' => 0,
                'name' => 'user',
                'description' => 'User',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'parent_id' => 3,
                'name' => 'user-update',
                'description' => 'User Update',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'parent_id' => 3,
                'name' => 'user-list',
                'description' => 'User List',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'parent_id' => 3,
                'name' => 'user-delete',
                'description' => 'User Delete',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'parent_id' => 0,
                'name' => 'reports',
                'description' => 'Reports',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'parent_id' => 7,
                'name' => 'view-reports',
                'description' => 'View Reports',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'parent_id' => 0,
                'name' => 'roles',
                'description' => 'Roles',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'parent_id' => 9,
                'name' => 'list-roles',
                'description' => 'Role List',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'parent_id' => 9,
                'name' => 'create-roles',
                'description' => 'Create Role',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'parent_id' => 9,
                'name' => 'update-roles',
                'description' => 'Update Roles',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'parent_id' => 9,
                'name' => 'delete-roles',
                'description' => 'Delete Role',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'parent_id' => 0,
                'name' => 'staff-management',
                'description' => 'Staff Management',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'parent_id' => 14,
                'name' => 'create-staff-management',
                'description' => 'Create Staff Management',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'parent_id' => 14,
                'name' => 'update-staff-management',
                'description' => 'Update Staff Management',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'parent_id' => 14,
                'name' => 'delete-staff-management',
                'description' => 'Delete Staff Management',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'parent_id' => 0,
                'name' => 'feedback',
                'description' => 'Feedback',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'parent_id' => 18,
                'name' => 'view-feedback',
                'description' => 'View Feedback',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'parent_id' => 0,
                'name' => 'rating',
                'description' => 'Rating',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'parent_id' => 20,
                'name' => 'view-rating',
                'description' => 'View Rating',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'parent_id' => 0,
                'name' => 'invitation-code',
                'description' => 'Invitation Code',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'parent_id' => 22,
                'name' => 'view-invitation-code',
                'description' => 'View Invitation Code',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'parent_id' => 22,
                'name' => 'create-invitation-code',
                'description' => 'Create Invitation Code',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'parent_id' => 0,
                'name' => 'policy-page',
                'description' => 'Policy Page',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'parent_id' => 25,
                'name' => 'view-policy-page',
                'description' => 'View Policy Page',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'parent_id' => 0,
                'name' => 'about',
                'description' => 'About',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'parent_id' => 27,
                'name' => 'view-about',
                'description' => 'View About',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'parent_id' => 3,
                'name' => 'user-detail',
                'description' => 'Show User Detail',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'parent_id' => 25,
                'name' => 'update-policy-page',
                'description' => 'Update Policy Page',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'parent_id' => 25,
                'name' => 'delete-policy-page',
                'description' => 'Delete Policy Page',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'parent_id' => 0,
                'name' => 'email-test',
                'description' => 'Email Test',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'parent_id' => 32,
                'name' => 'view-email-test',
                'description' => 'View Email Test',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'parent_id' => 0,
                'name' => 'interests',
                'description' => 'Interests',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 35,
                'parent_id' => 34,
                'name' => 'list-interests',
                'description' => 'Interest List',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 36,
                'parent_id' => 34,
                'name' => 'create-interests',
                'description' => 'Create Interest',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 37,
                'parent_id' => 34,
                'name' => 'update-interests',
                'description' => 'Update Interest',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'parent_id' => 34,
                'name' => 'delete-interests',
                'description' => 'Delete Interest',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'parent_id' => 0,
                'name' => 'user-whitelist',
                'description' => 'User Whitelist',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 40,
                'parent_id' => 39,
                'name' => 'list-user-whitelist',
                'description' => 'User Whitelist List',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 41,
                'parent_id' => 39,
                'name' => 'create-user-whitelist',
                'description' => 'Create User Whitelist',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 42,
                'parent_id' => 39,
                'name' => 'update-user-whitelist',
                'description' => 'Update User Whitelist',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 43,
                'parent_id' => 39,
                'name' => 'delete-user-whitelist',
                'description' => 'Delete User Whitelist',
                'guard_name' => 'web',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }

    public function down(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Permission::truncate();
    }
}
