<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Policy;
use Illuminate\Support\Carbon;

class PolicySeeder extends Seeder
{
    public function run()
    {
        Policy::truncate();
        Policy::insert([
            [
                'title' => 'Privacy Policy',
                'slug' => 'privacy-policy',
                'content' => '<p>Privacy Policy</p>
<p>Effective as of: November 1, 2022</p>
<p>Connect App LLC, a Washington State limited liability company (&ldquo;<strong>Company</strong>&rdquo;, &ldquo;<strong>Connect LLC</strong>&rdquo;, &ldquo;<strong>us</strong>&rdquo; or &ldquo;<strong>we</strong>&rdquo;) respects the privacy of those who use our Services (&ldquo;<strong>Users</strong>&rdquo; or &ldquo;<strong>you</strong>&rdquo;). We believe in the need for transparency when collecting and using your Personal Information. We are committed to that notion of transparency by protecting it through our compliance with this policy.</p>
<p>We know you care about what information may be collected from and about you, how such information is used and shared, and the choices you have.</p>
<p>Accordingly, this policy (&ldquo;<strong>Privacy Policy</strong>&rdquo;) explains how we collect, use, and disclose your personal and other information through the Cennec website, https://www.cennec.com, (the &ldquo;<strong>Website</strong>&rdquo;) or the Cennec mobile application (the &ldquo;<strong>Application</strong>,&rdquo; together with the Website the &ldquo;<strong>Services</strong>&rdquo;). We will treat your information in a manner consistent with this Privacy Policy unless you have consented otherwise. Also, you may opt-out of certain uses and disclosures of your information, as further explained in this Privacy Policy.</p>
<p>Please read this policy carefully to understand our policies and practices regarding your information and how we will treat it. By accessing and using the Services, you consent to the collection, use, and disclosure of your information in accordance with this Privacy Policy and you agree to be legally bound by its terms. This Policy may change from time to time. Your continued use of the Services after we make changes is deemed to be acceptance of those changes, so please check the policy periodically for updates.</p>
<p>IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS OF THIS PRIVACY POLICY, YOU MAY NOT ACCESS OR USE THE SERVICES. USE OF THE SERVICES IS GOVERNED BY, AND SUBJECT TO, OUR TERMS AND CONDITIONS, AND THIS PRIVACY POLICY IS INCORPORATED THEREIN. YOUR USE OR ACCESSING OF THE SERVICES CONSTITUTES YOUR AGREEMENT TO BE BOUND BY THE TERMS AND CONDITIONS.</p>
<p><strong>Children under the age of 18.</strong></p>
<p>Services are general use and are not targeted toward anyone under the age of 18 years of age or the age of majority in your jurisdiction, whichever is or older.</p>
<p>We are committed to the preservation of online privacy for all of our Users, especially children. the Services are intended for use exclusively by adults (i.e., those age 18 or older). We will not knowingly collect any Personal Information from children under the age of 18. If you are the parent or guardian of a child under the age of 18, and you become aware that Personal Information from a child under 18 has been collected by us, please contact us at [Email address].</p>
<p>California residents under 16 years of age may have additional rights regarding the collection and sale of their Personal Information, although we do not sell Personal Information of any User. Please refer to &ldquo;California Privacy Rights.&rdquo;</p>
<p><strong>Personal information we collect</strong>.</p>
<p>In order to establish your account and/or provided more tailored Services to you, we may receive from you the following types of Personal Information:</p>
<ol type="a">
    <li>
        <p><strong>Personal identifiers and characteristics (&ldquo;Personal Information&rdquo;)</strong>. We collect information such as (i) passport number and/or driver&rsquo;s license number for verification purposes, (ii) contact information (including your name, email address, postal address, and telephone number), (iii) gender, race or ethnic origin, (iv) political opinions, religious, philosophical, moral beliefs, (v) social welfare, sexual orientation, and/or marital status, (vi) age/date of birth, (vii) professional, education information and other demographic information, (viii) payment method and payment information, (ix) authentication information you create (such as account password), (x) and device identifiers (such as advertising IDs, pixel and cookie IDs, IP address, ICCID), and (xi) other Personal Information collected through the Services.</p>
    </li>
    <li>
        <p><strong>Usage Data</strong>. We reserve the right to collect information based on your usage of the Services which is information collected automatically by us or by third party services we have engaged for that purpose, which can include: the IP addresses or domain names of the computers utilized by the Users who use the Services, the URI (Uniform Resource Identifier) addresses, the time of the request, the method utilized to submit the request to the server, the size of the file received in response, the numerical code indicating the status of the server&apos;s answer (successful outcome, error, etc.), the country of origin, the features of the browser and the operating system utilized by the User, the various time details per visit (e.g., the time spent on each page within the Services) and the details about the path followed within the Services with special reference to the sequence of pages visited, other parameters about the device operating system and/or the User&apos;s IT environment, and data, conversion rates, marketing and conversion data and statistics, reports, analytics data, reviews and surveys (&ldquo;<strong>Usage Data</strong>&rdquo;). Usage Data is essentially anonymous when collected, but could be used indirectly to identify a person.</p>
    </li>
    <li>
        <p><strong>Geolocation information</strong>, such as IP-based or precise geolocation information. This may be collected automatically or based on information you provide.</p>
    </li>
    <li>
        <p><strong>Your marketing preferences</strong>, such as your online interested-based information including things you click or other sites you visit during your browsing session.</p>
    </li>
    <li>
        <p><strong>User information required for your contract with us</strong>, invoicing data, and also service usage data that prove that the service is used in accordance to your subscription terms, We may also acquire additional data through our Users&rsquo; support requests to the extent this is required for us to resolve a technical issue or respond to a request or complaint. We may also email to our Users newsletters, announcements regarding the Company and our products, or marketing material. If you no longer wish to receive such emails, you can remove yourself from the recipients list at any time by selecting the &ldquo;unsubscribe&rdquo; link provided within the e-mail footer. If you are providing information (including Personal Information) about someone else, you must have the authority to act for them and to consent to the collection and use of their Personal Information.</p>
    </li>
    <li>
        <p><strong>Content that you create, input, submit, post, upload, transmit, store or display&nbsp;</strong>in the process of using the Services. Such Content includes any Personal Information or other sensitive information that you choose to include (&ldquo;<strong>incidentally-collected Personal Information</strong>&rdquo;). Although the Company owns the code, databases, and all rights to the Services and any related service, Users retain ownership, control and all rights to their records and data, which are their property.</p>
    </li>
</ol>
<p><strong>How we collect the information.</strong></p>
<p>We collect Personal Information about you from the following sources:</p>
<ol type="a">
    <li>
        <p><strong>Directly From You</strong>. We may collect Personal Information during your access or use of the Services and through other online and offline interactions. For example, when you provide information to enable us to match you with other Users on our Services, when you sign up for marketing, make purchases, create an account, contact us for customer service or other assistance, and participate in promotions.</p>
    </li>
    <li>
        <p><strong>Cookies and Tracking Technologies</strong>. When you access or use the Services, we may collect data about your device, internet usage, location, website activity, and other details about your use of the Services through cookies and other tracking technologies. For further information on these practices, see &ldquo;Cookies and Other Tracking Technologies.&rdquo;</p>
    </li>
    <li>
        <p><strong>Other Third Parties and Publicly Available Information</strong>. We may collect Personal Information from other third parties that provide information to us, such as advertising networks, government and other public sources, and social media platforms and networks. We <em>do not</em> sell or otherwise provide your Personal Information to third parties for their own business uses, including but not limited to marketing.</p>
    </li>
</ol>
<p><strong>How we use your Personal Information.</strong></p>
<p>We may combine information that we receive from the various sources described in this Privacy Policy, including third-party sources, and use or disclose it for the following purposes:</p>
<ol type="a">
    <li>
        <p>To provide you with the Services and to respond to your inquiries, process transactions and payments, fulfill your order, communicate with you, authenticate Users, verify your eligibility for certain programs or benefits, and otherwise facilitate your relationship with us and other Users.</p>
    </li>
    <li>
        <p>To facilitate matches with other people and to optimize the chances matches will become an ideal connection.</p>
    </li>
    <li>
        <p>For marketing, such as to market the Services or goods and services of those of our affiliates or other third parties.</p>
    </li>
    <li>
        <p>For insights, such as to identify trends and make inferences about you and your interactions with us or our affiliates, such as to analyze your behavior and preferences, and to evaluate and improve the products and services of our affiliates. We reserve the right to participate with third party analytics partners to monitor and analyze Web traffic and can be used to keep track of User behavior on the Services. We use Amazon Web Services (&ldquo;AWS&rdquo;) for these purposes. Information about how AWS treats data it has access to as a customer of the Company is available from AWS in the form of <a href="https://aws.amazon.com/compliance/data-privacy-faq/">Data Privacy FAQ</a>.</p>
    </li>
    <li>
        <p>To comply with legal obligations, including keeping records required by law or to evidence our compliance with laws or to provide information to law enforcement.</p>
    </li>
    <li>
        <p>For internal business and operational purposes, such as:</p>
        <ol type="i">
            <li>
                <p>For our internal business administration, such as managing User accounts, including keeping general records of Users, sales, customer care, and other interactions;</p>
            </li>
            <li>
                <p>Auditing related to our interactions with you;</p>
            </li>
            <li>
                <p>for security purposes, such as to protect genuine Users and our business from fraud, to minimize the risk of false details being used, and to avoid abuse by fraudsters;</p>
            </li>
            <li>
                <p>to manage competitions or other promotions that you have chosen to participate in;</p>
            </li>
            <li>
                <p>to comply with contractual obligations;</p>
            </li>
            <li>
                <p>to improve or develop our products and services (including our marketing activity more generally), including operating the Services and improving or personalizing your experience (such as building profiles about you or how you interact with us); and</p>
            </li>
            <li>
                <p>for internal research and quality assurance.</p>
            </li>
        </ol>
    </li>
    <li>
        <p>Business Transfers in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company. You will be notified on any change in ownership or uses of your Personal Information, as well as any choices you may have regarding your Personal Information.</p>
    </li>
</ol>
<p>We may use de-identified, anonymized, pseudonymized, or aggregated versions of your Personal Information for any purpose.</p>
<p><strong>How we share your Personal Information.</strong></p>
<p>We and our affiliates may share your information with each other. We may also share your Personal Information with third parties in the ways that are described in this Privacy Policy.</p>
<ol type="a">
    <li>
        <p><strong>Affiliates</strong>: We may share your Personal Information with our affiliates, partners, employees, officers, and agents.</p>
    </li>
    <li>
        <p><strong>With Third Parties to Provide You with Services or Communications</strong>: We may disclose your information to third parties to provide you with services or benefits such as fixing product bugs, technical development and strategic planning.</p>
    </li>
    <li>
        <p><strong>With others for Legal, Security, or Safety Purposes</strong>: We may share your Personal Information (i) as required by law or legal process; (ii) to prevent or investigate suspected or possible fraud, harassment, or other violations of any law, rule, or regulation; and (iii) to prevent or investigate suspected or possible violations of any terms or policies applicable to the Services or other services provided by us or our third party providers or affiliates.</p>
    </li>
    <li>
        <p><strong>In Connection with a Corporate Transaction</strong>: We also may transfer your Personal Information in connection with a sale, merger, change of control, bankruptcy, or similar transaction.</p>
    </li>
    <li>
        <p><strong>NOT With Business Partners for their Own Purposes</strong>: We will not share your Personal Information with business partners or other third parties for their own purposes.</p>
    </li>
    <li>
        <p><strong>With other third parties with your consent</strong>.&zwj;</p>
    </li>
</ol>
<p><strong>Cookies and other tracking technologies</strong>.</p>
<p>Like many other websites and applications, we may automatically collect certain information regarding Users. Such information may include, without limitation, the Internet Protocol (&ldquo;<strong>IP</strong>&rdquo;) address (which may be used to determine your geographic location) of your computer/internet service provider, your device ID, your zip code, the date and time you access the Services, the Internet address of a referring website, the operating system you are using, the sections or pages of the Services that you visit, and the images and content viewed. Some of the ways in which we or the website may collect and use such information are further described below.</p>
<p>The Website uses cookies, a type of technology that installs a small amount of information on a User&apos;s computer or other device when they visit a website. Cookies permit a website to recognize future visits using that computer or device. The Website uses cookies and similar technologies on the Website to customize your visit, to enhance our service, or for other purposes. For example, information provided through cookies is used to recognize you as a previous User of the Website and to offer personalized content. We may also use and share such information to personalize marketing (for The Company or for our affiliates, as further described in this Privacy Policy). You may choose to decline cookies by adjusting your browser preferences but doing so may affect your use of the Website and your ability to access certain features of the Website. Cookies and similar technologies may be used by our affiliates, a tracking utility company, and other parties to make it easier for you to navigate to our Website, serve advertisements, and other purposes. We do not have access to or control over these cookies and technologies and we cannot state whether these parties will comply with this Privacy Policy.</p>
<p>Pages of the Website and our e-mails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count Users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of certain website content and verifying system and server integrity).</p>
<p>Information collected by cookies and other tracking technologies may be collected and shared for the purposes described in this Privacy Policy. We may also use the data to build a better picture of the type of offers and products that you might be interested in, for &ldquo;Interest-Based Advertising&rdquo; (described below) and push notifications. We also may use general location data, preferences, or other information received from the Services to send you tailored marketing messages, including making product recommendations. We may also anonymize or aggregate any information collected using cookies and other tracking technologies and may use and share such data for any lawful purpose.</p>
<p><strong>Interest-Based Advertising</strong>.</p>
<p>We may use the information we collect (alone or in combination with information provided by third parties and service providers) to deliver targeted advertising (about the Company or other third-party products and services) to you when you visit the Services or other websites. Information about you (such as email address) as well as cookies and other tracking technologies (described above) may be used in this process. For example, if you are searching for information on a particular product, we may use that information to cause an advertisement to appear on other websites you view with information on that product.</p>
<p>If you would like to opt-out of these interest-based advertisements, please see the Opt-Out Process/Options and Additional Terms below.</p>
<p><strong>Data Retention</strong>.</p>
<p>We will retain your Personal Information for as long as your account is active (as determined by us) and for a reasonable time thereafter, or such other time period as prescribed by law. We also may retain your Personal Information for a longer period of time as needed to provide you services or as necessary to comply with our legal obligations, to resolve disputes, and to enforce our agreements. Even if we delete some or all of your Personal Information, we may continue to retain and use aggregate, anonymous data previously collected and/or anonymize and aggregate your Personal Information.</p>
<p><strong>Updating personal Information.</strong></p>
<p>Upon request, we will permit you to request or make changes or updates to your Personal Information for legitimate purposes. We require User verification prior to approving such requests. We reserve the right to decline any requests that are unreasonably repetitive or systematic, require unreasonable time or effort of our technical or administrative personnel, or undermine the privacy rights of others. We reserve the right to permit you to access your Personal Information in any account you establish with the Services for purposes of making your own changes or updates, and in such case, instructions for making such changes or updates will be provided where necessary.</p>
<p><strong>Contests and Promotions.</strong></p>
<p>If contests or promotions are made available, the applicable contest or promotion rules may include rules regarding the collection, use, and disclosure of Personal Information. To the extent that those specific rules conflict with this Privacy Policy, the contest or promotion rules will supersede this Privacy Policy with respect to the conflicting terms and the non-conflicting terms of this Privacy Policy and our Terms and Conditions will continue to apply.</p>
<p><strong>Your Choices.</strong></p>
<p>We strive to provide you with choices about how information is used and shared. There are several ways in which you may opt out of the various programs and services we provide. Some of the ways in which you may opt out are described below.</p>
<p><strong>Opting Out of Our Services.</strong> If you receive a marketing email from us, you may unsubscribe from future marketing emails in accordance with our standard unsubscribe process.</p>
<p><strong>Interest-Based Advertising Opt-Out and Do Not Track Signals.</strong> With respect to &ldquo;do not track&rdquo; (a/k/a &ldquo;<strong>DNT</strong>&rdquo;) signals or similar mechanisms transmitted by web browsers, the Website does not respond to or honor such signals or mechanisms. This means that third parties, such as ad networks, web analytics companies, and social networking platforms (some of whom are discussed elsewhere in this Privacy Policy), may collect information about your online activities over time and across our Website and other third-party online properties or services. These companies may use information about your visits to our Website and other sites, and general geographic information derived from your IP address, in order to provide advertisements about goods and services of interest to you. For more information about third-party advertisers and how to prevent them from using your information, please visit http://www.networkadverDsing.org/choices/. This is a site offered by the Network Advertising Initiative (&ldquo;<strong>NAI</strong>&rdquo;) that includes information on how consumers can opt- out from receiving interest-based advertising from some or all of NAI&apos;s members. You can also visit http://www.aboutads.info/choices, which is a site offered by the Digital Advertising Alliance (&ldquo;<strong>DAA</strong>&rdquo;) that includes information on how consumers can opt-out from receiving internet-based advertising from some or all of DAA&apos;s participating companies. Opting out of interest-based advertising does not mean that you will no longer see any advertisements; rather, you will still see advertisements that are general and not tailored to your specific interests and activities. Further, cookie-based opt-outs must be performed on each device and browser that you wish to have opted-out.</p>
<p>We do not control third parties&apos; collection or use of your information to serve interest-based advertising. However, these third parties may provide you with ways to choose not to have your information collected or used in this way.</p>
<p><strong>Data Security.</strong></p>
<p>We will implement reasonable and appropriate security procedures consistent with prevailing industry standards to protect data from unauthorized access by physical and electronic intrusion. Unfortunately, no data transmission over the Internet or method of data storage can be guaranteed 100% secure. Therefore, while we strive to protect your Personal Information by following generally accepted industry standards, we cannot ensure or warrant the absolute security of any information you transmit to us or archive at the Services.</p>
<p>When you transmit Personal Information through our registration process or if you purchase products or services, we encrypt that information in transit using secure socket layer technology (SSL). We do not store your credit card information in our systems. All credit card transactions are processed using secure encryption - the same level of encryption used by leading banks. Card information is transmitted, stored, and processed securely at gateways on a PCI-compliant network.</p>
<p><strong>Compliance with Laws and Law Enforcement.</strong></p>
<p>We cooperate with government and law enforcement officials and private parties to enforce and comply with the law. We will disclose any information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate to respond to claims and legal process (including but not limited to subpoenas), to protect the property and rights of the Company or a third party, to protect the safety of the public or any person, or to prevent or stop any activity we may consider to be, or to pose a risk of being, illegal, unethical, inappropriate or legally actionable.</p>
<p><strong>California &ldquo;Shine the Light&rdquo;.</strong></p>
<p>Under California Civil Code Section 1798.83 (&ldquo;Shine the Light&rdquo;), California residents have the right to request in writing from businesses with whom they have an established business relationship: (a) a list of the categories of Personal Information, as defined under Shine the Light, such as name, email address and mailing address and the type of services provided to the customer that a business has disclosed to third parties (including affiliates that are separate legal entities) during the immediately preceding calendar year for the third parties&rsquo; direct marketing purposes; and (b) the names and addresses of all such third parties. If you are a California resident: (i) to request the above information, or (ii) if you do not want your Personal Information shared with any third party who may use such information for direct marketing purposes and wish to opt out of such disclosures, please contact us by email at [email Address]. PLEASE NOTE: WE DO NOT SHARE USER INFORMATION WITH THIRD PARTIES FOR THEIR OWN BUSINESS OR MARKETING PURPOSES.</p>
<p>If we did share our User&rsquo;s Personal Information with third parties for their own marketing purposes (which we do not), under Shine the Light, we would not be responsible for removing your Personal Information from the lists of any third party who has previously been provided with your information, and any elections or privacy choices you may make with respect to receipt of certain types of e-mails or marketing communications from us would not apply to any such third parties. You would need to directly contact any third parties that send you communications regarding choices that they may make available to you concerning such communications.</p>
<p><strong>Nevada Privacy Rights.</strong></p>
<p>If you are a Nevada resident, you have the right to request that we do not sell your covered information (as those terms are defined in N.R.S. 603A) that we have collected, or may collect, from you. We do not sell your covered information; however, if you would like to make such a request you may do so by contacting us at [email address]</p>
<p><strong>Your California Privacy Rights.</strong></p>
<p>We collect information that identifies, relates to, describes, references, or is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or household. The California Consumer Privacy Act of 2018 (&ldquo;<strong>CCPA</strong>&rdquo;) refers to such information as &ldquo;Personal Information.&rdquo; To the extent that we, as a company, are subject to CCPA, if you are a California consumer (as defined by the CCPA) the CCPA provides you with specific rights regarding your Personal Information. More information regarding the CCPA can be found at <a href="https://oag.ca.gov/privacy/ccpa">https://oag.ca.gov/privacy/ccpa</a>.</p>
<p><strong>(GDPR), (UK DPA) and other Data Protection laws.</strong></p>
<p>IF YOU ARE SITUATED IN THE EUROPEAN ECONOMIC AREA (&ldquo;<strong>EU</strong>&rdquo;), SWITZERLAND, OR THE UNITED KINGDOM (the &ldquo;<strong>UK</strong>&rdquo;), THIS SECTION APPLIES TO OUR COLLECTION, USE, AND DISCLOSURE OF YOUR PERSONAL DATA AND ADDITIONAL RIGHTS YOU HAVE UNDER APPLICABLE LAW.</p>
<p>The Company is located in the United States. If you are accessing the Services from outside of the United States, your use of the Services constitutes consent to transfer and process your personal data in the Unites States, and our Data Processing Addendum applies (see below).</p>
<p><strong>Privacy Policy Changes.</strong></p>
<p>We have the sole discretion to change, modify, add, or remove portions of this Privacy Policy from time to time. New versions of this Privacy Policy will be posted here. Our collection, use and disclosure of your information will be governed by the version of this Privacy Policy in effect at the time of such collection, use or disclosure. If we materially change the way that we collect, use or disclose your Personal Information, we will notify you through a notice, updated Privacy Policy on the Website, or by email (sent to the email address specified in your account), prior to or upon the change(s) becoming effective. Accordingly, when you access or use the Services, you should check the date of this Privacy Policy and be aware of any changes since the last version. Your continued use of the Services following the posting of any changes to this Privacy Policy means that you accept such changes.</p>
<p><strong>Contact.</strong></p>
<p>You may contact us at:</p>
<p>Connect App LLC</p>
<p>Attn: Privacy Policy Officer</p>
<p>[address]</p>
<p>Email: [email address]</p>
<p><strong>Data Processing Addendum</strong></p>
<p>This Data Processing Addendum (&ldquo;<strong>DPA</strong>&rdquo;) forms part of the Connect App LLC Privacy Policy, updated from time to time between you and/or the entity you represent (&ldquo;<strong>Client</strong>&rdquo;) and Connect App LLC (the &ldquo;<strong>Company</strong>&rdquo;) when GDPR applies to your use of Services between the Client and the Company.</p>
<p><strong>1. Definitions and Interpretation</strong></p>
<p>a. Unless otherwise defined herein, capitalized terms and expressions used in this Agreement shall have the following meaning:</p>
<p>i. &ldquo;Agreement&rdquo; means this Data Processing Agreement and all Schedules;</p>
<p>ii. &ldquo;Client Personal Data&rdquo; means any personal data Processed by the Company or a Contracted Processor on behalf of a Client or User pursuant to or in connection with the Principal Agreement;</p>
<p>iii. &ldquo;Contracted Processor&rdquo; means a Sub processor;</p>
<p>iv. &ldquo;Data Protection Laws&rdquo; means EU Data Protection Laws and, to the extent applicable, the data protection or privacy laws of any other country;</p>
<p>v. &ldquo;EEA&rdquo; means the European Economic Area;</p>
<p>vi. &ldquo;EU Data Protection Laws&rdquo; means EU Directive 95/46/EC, as transposed into domestic legislation of each Member State and as amended, replaced or superseded from time to time, including by the GDPR and laws implementing or supplementing the GDPR;</p>
<p>vii. &ldquo;GDPR&rdquo; means EU General Data Protection Regulation 2016/679;</p>
<p>viii. &ldquo;Data Transfer&rdquo; means:</p>
<ol type="a">
    <li>
        <p>a transfer of Client personal data from the Company to a Contracted Processor; or</p>
    </li>
    <li>
        <p>an onward transfer of Client personal data from a Contracted Processor to Contracted Processor, in each case, where such transfer would be prohibited by Data Protection Laws (or by the terms of data transfer agreements put in place to address the data transfer restrictions of Data Protection Laws);</p>
    </li>
</ol>
<p>ix. &ldquo;Services&rdquo; means the services provided by the Company.</p>
<p>x. &ldquo;Sub processor&rdquo; means any person appointed by or on behalf of Processor to process Client personal data on behalf of the Company in connection with the Agreement.</p>
<p>xi. The terms, &ldquo;Commission&rdquo;, &ldquo;Controller&rdquo;, &ldquo;Data Subject&rdquo;, &ldquo;Member State&rdquo;, &ldquo;Personal Data&rdquo;, &ldquo;personal data Breach&rdquo;, &ldquo;Processing&rdquo; and &ldquo;Supervisory Authority&rdquo; shall have the same meaning as in the GDPR, and their cognate terms shall be construed accordingly.</p>
<p><strong>2. Processing of Client Personal Data</strong></p>
<p>a. Processor shall:</p>
<p>i. comply with all applicable Data Protection Laws in the Processing of Client Personal Data; and</p>
<p>ii. not Process Client personal data other than on the relevant Client&rsquo;s documented instructions.</p>
<p>b. The Company instructs Processor to process Client Personal Data.</p>
<p><strong>3. Processor Personnel</strong></p>
<p>a. Processor shall take commercially reasonable steps to ensure the reliability of any employee, agent or contractor of any Contracted Processor who may have access to Client Personal Data, ensuring in each case that access is strictly limited to those individuals who need to know / access the relevant Client Personal Data, as strictly necessary for the purposes of the Principal Agreement, and to comply with Applicable Laws in the context of that individual&rsquo;s duties to the Contracted Processor, ensuring that all such individuals are subject to confidentiality undertakings or professional or statutory obligations of confidentiality.</p>
<p><strong>4. Security</strong></p>
<p>a. Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of Processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, Processor shall in relation to Client personal data implement appropriate technical and organizational measures to ensure a level of security appropriate to that risk, including, as appropriate, the measures referred to in Article 32(1) of the GDPR.</p>
<p>b. In assessing the appropriate level of security, the Processor shall take into account in particular the risks that are presented by Processing, in particular from a personal data Breach.</p>
<p><strong>5. Sub Processing</strong></p>
<p>a. Processor shall only appoint and or disclose Client personal data to authorized Sub Processors and shall do so only if required by The Company.</p>
<p>b. Taking into account the nature of the Processing, Processor shall assist the Company by implementing appropriate technical and organizational measures, insofar as this is possible, for the fulfillment of Company obligations, as reasonably understood by Client, to respond to requests to exercise Data Subject rights under the Data Protection Laws.</p>
<p>c. <strong>Processor shall</strong>:</p>
<p>i. promptly notify Client if it receives a request from a Data Subject under any Data Protection Law in respect of Client Personal Data; and</p>
<p>ii. ensure that it does not respond to that request except on the documented instructions of Client or as required by Applicable Laws to which the Processor is subject, in which case Processor shall to the extent permitted by Applicable Laws inform Client of that legal requirement before the Contracted Processor responds to the request.</p>
<p>d. <strong>Personal Data Breach</strong>:</p>
<p>i. Processor shall notify Client without undue delay upon Processor becoming aware of a personal data Breach affecting Client Personal Data, providing Client with sufficient information to allow the Company to meet any obligations to report or inform Data Subjects of the personal data Breach under the Data Protection Laws.</p>
<p>ii. Processor shall cooperate with the Company and take reasonable commercial steps as directed by Client to assist in the investigation, mitigation and remediation of each such personal data Breach.</p>
<p><strong>6. Data Protection Impact Assessment and Prior Consultation Processor.</strong> Prior Consultation Processor shall provide reasonable assistance to the Company with any data protection impact assessments, and prior consultations with Supervising Authorities or other Protection Law, in each case solely in relation to Processing of Client personal data by, and taking into account the nature of the Processing and information available to, the Contracted Processors.</p>
<p><strong>7. Deletion or return of Client Personal Data.&nbsp;</strong>Subject to this section 9 Processor shall promptly and in any event within 10 business days of the date of cessation of any Services involving the Processing of Client personal data (the &ldquo;<strong>Cessation Date</strong>&rdquo;), delete and procure the deletion of all copies of those Client Personal Data.</p>
<p><strong>8. Audit Rights</strong></p>
<p>a. Processor shall make available to The Company on request all information necessary to demonstrate compliance with this Agreement, and shall allow for and contribute to audits, including inspections, by The Company or an auditor mandated by The Company in relation to the Processing of Client personal data by the Contracted Processors.</p>
<p>b. Information and audit rights of The Company only arise under section 10.1 to the extent that the Agreement does not otherwise give them information and audit rights meeting the relevant requirements of Data Protection Law.</p>
<p><strong>9.</strong> <strong>Data Transfer</strong> The Processor may not transfer or authorize the transfer of Data to countries outside the EU and/or the European Economic Area (EEA) without the prior written consent of the Company. If personal data processed under this Agreement is transferred from a country within the European Economic Area to a country outside the European Economic Area, the Parties shall ensure that the personal data are adequately protected. To achieve this, the Parties shall, unless agreed otherwise, rely on EU approved standard contractual clauses for the transfer of personal data.</p>
<p><strong>10. General Terms</strong></p>
<p>a. <strong>Confidentiality</strong>. Each Party must keep this Agreement and information it receives about the other Party and its business in connection with this Agreement (&ldquo;<strong>Confidential Information</strong>&rdquo;) confidential and must not use or disclose that Confidential Information without the prior written consent of the other Party except to the extent that:</p>
<p>i. disclosure is required by law; or</p>
<p>ii. the relevant information is already in the public domain.</p>
<p>b. <strong>Notices</strong>. All notices and communications given under this Agreement must be in writing and will be delivered personally, sent by post or sent by email to the address or email address set out in the heading of this Agreement at such other address as notified from time to time by the Parties changing address.</p>
<p><strong>11. Governing Law and Jurisdiction</strong></p>
<p>a. This Agreement is governed by the laws of the state of Washington.</p>
<p>b. Any dispute arising in connection with this Agreement, which the Parties will not be able to resolve amicably, will be submitted to the exclusive jurisdiction of the courts of the state of Washington.</p>',
                'policies_status' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Terms and Conditions',
                'slug' => 'terms-conditions',
                'content' => '<p>Connect App LLC - Terms and Conditions</p>
<p><em>Last modified: November 1, 2022</em></p>
<p><span size="3">Welcome to Cennec, where we help you connect, minus the dating! These Terms and Conditions (these &ldquo;</span><span size="3"><strong>Terms</strong></span><span size="3">&rdquo;) apply to the use of this website (the &ldquo;</span><span size="3"><strong>Website</strong></span><span size="3">&rdquo;) and the Cennec mobile application (the &ldquo;</span><span size="3"><strong>Application</strong></span><span size="3">,&rdquo; together with the Website, the Documentation (as defined below) and the Software (as defined below), the &ldquo;</span><span size="3"><strong>Services</strong></span><span size="3">&rdquo;) by customers (&ldquo;</span><span size="3"><strong>Customers</strong></span><span size="3">,&rdquo; &ldquo;</span><span size="3"><strong>Users</strong></span><span size="3">,&rdquo; or &ldquo;</span><span size="3"><strong>you</strong></span><span size="3">&rdquo;) from Connect App LLC, a Washington limited liability company (&ldquo;</span><span size="3"><strong>Connect LLC</strong></span><span size="3">,&rdquo; &ldquo;</span><span size="3"><strong>us</strong></span><span size="3">,&rdquo; or&nbsp;</span><span size="3"><strong>we</strong></span><span size="3">&rdquo;). These Terms shall become effective on the earlier of the date you first access or use the Services and the date set forth in the applicable order (the &ldquo;</span><span size="3"><strong>Effective Date</strong></span><span size="3">&rdquo;). Connect LLC, User, and Customer are sometimes referred to in these Terms collectively as &ldquo;</span><span size="3"><strong>Parties</strong></span><span size="3">&rdquo; and individually as a &ldquo;</span><span size="3"><strong>Party</strong></span><span size="3">.&rdquo; If the person accepting these Terms is doing so on behalf of a company or other legal entity, that person represents that he or she has the authority to bind the company or entity to these Terms.&nbsp;</span><span size="3"><strong>If you do not agree to these Terms, you are NOT authorized to use Services.&nbsp;</strong></span></p>
<p><strong>BY USING THE SERVICES, YOU AGREE TO PARTICIPATE IN ARBITRATION AND WAIVE YOUR RIGHT TO CLASS ACTION AS DESCRIBED IN SECTION 13 WITH RESPECT TO ANY DISPUTES OR CONFLICTS WITH CONNECT LLC.</strong></p>
<p><strong>You affirm that you are 18 or more years of age on the date, and at the location at which, you click on &ldquo;I Agree,&rdquo; and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms, and to abide by and comply with these Terms.</strong></p>
<p>1. DEFINITIONS. The following terms shall have the following definitions:</p>
<p>&ldquo;<span size="3"><strong>Administrator</strong></span>&rdquo; means an individual to whom Customer has granted certain administrative control rights over Customer, including, but not limited to, the right to view content submitted by Customers.</p>
<p>&ldquo;<span size="3"><strong>Content</strong></span>&rdquo; means any information that has been collected by the Services from any person at any time.</p>
<p>&ldquo;<span size="3"><strong>Documentation</strong></span>&rdquo; means any written or electronic user guides, instructions, help and training materials, technical materials, or other documentation Connect LLC provides regarding use of the Services.</p>
<p>&ldquo;<span size="3"><strong>Force Majeure Event</strong></span><span size="3">&rdquo; means any act or event that (a) prevents a Party (the &ldquo;</span><span size="3"><strong>Nonperforming Party</strong></span><span size="3">&rdquo;) from performing its obligations or satisfying a condition to the other Party&rsquo;s (the &ldquo;</span><span size="3"><strong>Performing Party</strong></span><span size="3">&rdquo;) obligations under these Terms, (b) is beyond the reasonable control of and not the fault of the Nonperforming Party, and (c) the Nonperforming Party has not, through commercially reasonable efforts, been able to avoid or overcome. &ldquo;</span><span size="3"><strong>Force Majeure Event</strong></span>&rdquo; does not include economic hardship, changes in market conditions, or insufficiency of funds, but does include strikes, work stoppages, epidemics (but not financial hardship due to an epidemic), acts of war or terrorism, civil or military disturbances, nuclear or natural catastrophes or acts of God, and interruptions, loss or malfunctions of utilities, communications or computer (software and hardware) services.</p>
<p>&ldquo;<span size="3"><strong>Intellectual Property Rights</strong></span>&rdquo; means patent rights (including patent applications and disclosures), copyrights, moral rights, trademarks, service marks, trade secrets, rights in databases, know-how and any other intellectual property rights recognized in any country or jurisdiction in the world, now or hereafter existing, and whether or not perfected, filed or recorded.</p>
<p>&ldquo;<span size="3"><strong>Order</strong></span>&rdquo; means an electronic or written order or agreement form incorporating these Terms that sets forth the commercial details of Customer&rsquo;s subscription to a Connect LLC Services, sets forth the fees for such Services, and is signed by an authorized representative of each Party.</p>
<p>&ldquo;<span size="3"><strong>Software</strong></span>&rdquo; means all computer software underlying the Services, including, without limitation, software (in object or source code form), programming code, scripts, and HTML code contained in the Services.</p>
<p>&ldquo;<span size="3"><strong>Services</strong></span>&rdquo; means Connect LLC&rsquo;s business services including, but not limited to, the Cennec service and all features relating to such service. Without limiting the foregoing, Services includes the Software and Documentation.</p>
<p>2. SERVICES &amp; USE.</p>
<p><span size="3">2.1&nbsp;</span><span size="3"><strong>Services</strong></span>. Subject to these Terms, and in consideration of the fees relating to Customer&rsquo;s use of the Services, Connect LLC will use commercially reasonable efforts to make the Services available to Customer. Connect LLC hereby grants Customer a revocable, non-exclusive, non-transferable, non-sublicensable right to access and use the Services pursuant to these Terms and in accordance with the Documentation. All rights in and to the Services not expressly granted herein are reserved to Connect LLC.</p>
<p><span size="3">2.2&nbsp;</span><span size="3"><strong>Use Restrictions</strong></span><span size="3">. You agree that you are responsible for your own conduct and User content while using the Services, and for any consequences thereof. In addition, you agree not to do any of the following, unless applicable law mandates that you be given the right to do so:&nbsp;</span></p>
<ul>
    <li>
        <p>collect, store or share any personally identifiable information of other users from the Services without their express permission?&nbsp;</p>
    </li>
    <li>
        <p>extract, scrape, or index the Services or Content (including information about users)?&nbsp;</p>
    </li>
    <li>
        <p>use the Services or Content, or any portion thereof, for any commercial purpose or in a manner not permitted by these Terms;&nbsp;</p>
    </li>
    <li>
        <p>attempt to access or search the Services or Content or download Content from the Services through the use of any technology such as, but not limited to, generally available third party web browsers (including without limitation automation software, bots, spiders, crawlers, data mining tools, or hacks, tools, agents, engines, or devices of any kind), other than those provided by Connect LLC?&nbsp;</p>
    </li>
    <li>
        <p>attempt to decipher, decompile, disassemble, or reverse engineer any of the Software used to provide the Services or Content?&nbsp;</p>
    </li>
    <li>
        <p>bypass, remove, deactivate, descramble, or otherwise circumvent any technological measure implemented by Connect LLC or any of Connect LLC&rsquo;s providers or any other third party (including another user) to protect the Services or Content?&nbsp;</p>
    </li>
    <li>
        <p>use, display, mirror, or frame the Services or any individual element within the Services, Connect LLC&rsquo;s name, any Connect LLC trademark, logo, or other proprietary information, or the layout and design of any page or App without Connect LLC&rsquo;s express written consent?&nbsp;</p>
    </li>
    <li>
        <p>post, publish, submit or transmit any Content that infringes, misappropriates, or violates a third party&rsquo;s patent, copyright, trademark, trade secret, moral rights, or other intellectual property rights, or rights of publicity or privacy?&nbsp;</p>
    </li>
    <li>
        <p>access, tamper with, or use nonpublic areas of the Services, Connect LLC&rsquo;s computer systems, or the technical delivery systems of Connect LLC&rsquo;s providers?&nbsp;</p>
    </li>
    <li>
        <p>attempt to probe, scan, or test the vulnerability of any Connect LLC system or network or Services, or breach any security or authentication measures?&nbsp;</p>
    </li>
    <li>
        <p>use any meta tags or other hidden text or metadata utilizing a Connect LLC trademark, logo, URL, or product name without Connect LLC&rsquo;s express written consent;&nbsp;</p>
    </li>
    <li>
        <p>forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services or Content to send altered, deceptive, or false source identifying information?&nbsp;</p>
    </li>
    <li>
        <p>interfere with, or attempt to interfere with, the access of any user, host, or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mailbombing the Services ?&nbsp;</p>
    </li>
    <li>
        <p>delete, obscure, or in any manner alter any attribution, warning, or link that appears in the Services or the Content?&nbsp;</p>
    </li>
    <li>
        <p>violate any applicable law or regulation? or&nbsp;</p>
    </li>
    <li>
        <p>encourage or enable any other individual to do any of the foregoing.&nbsp;</p>
    </li>
</ul>
<p><span size="3">Although Connect LLC is not obligated to monitor access to or use of the Services or Content or to review or edit any Content, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms, and to comply with applicable law or other legal requirements. We reserve the right to remove or disable access to any Content, at any time and without notice. Connect LLC may remove any Content we consider to be objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users and others who violate the law.&nbsp;</span></p>
<p>ANY ATTEMPT BY YOU TO DISRUPT OR INTERFERE WITH THE SERVICE, INCLUDING WITHOUT LIMITATION UNDERMINING OR MANIPULATING THE LEGITIMATE OPERATION OF ANY SERVICE, IS A BREACH OF CONNECT LLC&rsquo;S TERMS AND MAY BE A BREACH OR VIOLATION OF CRIMINAL AND CIVIL LAWS.</p>
<p><span size="3">2.3&nbsp;</span><span size="3"><strong>Login Credentials</strong></span>. Each set of login credentials for the Services may be used only by a single, individual Administrator. Customer agrees to promptly notify Connect LLC of any unauthorized access or use of which Customer becomes aware. Customer will be responsible for all use and misuse of the Services that occurs under any User&rsquo;s login credentials, and for any breach of these Terms by any Users.</p>
<p><span size="3">2.4&nbsp;</span><span size="3"><strong>Administrators</strong></span>. Customer shall designate one or more Administrators. Administrators shall have access to view User content and personal information submitted by Users.</p>
<p><span size="3">2.5&nbsp;</span><span size="3"><strong>Termination</strong></span>. Connect LLC retains the right to terminate your account, and any related service to you under its Services, if you are found in violation of these Terms or any other Connect LLC policy. Connect LLC may, under its sole discretion, delete, pause, or otherwise terminate your access to the Website and its Services for any reason and with or without notice.</p>
<p>3. USER CONTENT; PRIVACY POLICY.</p>
<p><span size="3">3.1&nbsp;</span><span size="3"><strong>Responsibility for User&rsquo;s Content and personal information</strong></span>. To the full extent legally permissible, Customer is solely responsible for all User Content and personal information, including, without limitation, the accuracy, quality, integrity, reliability, appropriateness, and legality of the User Content and information. Certain types of information within the content may be subject to specific regulations (e.g., regulations regarding personally identifiable information, protected health information, etc.). Customer, not Connect LLC, is responsible for compliance with all such regulations unless such compliance is specifically attributable under law to companies providing services equivalent to the Services. Without limiting the foregoing, Customer represents and warrants that, if applicable, Customer will provide any required notice to, and obtain any required consent from, individuals, including Users, related to the collection, use, or viewing of User&rsquo;s content and personal information.</p>
<p><span size="3">3.2&nbsp;</span><span size="3"><strong>Connect LLC&rsquo;s use of User&rsquo;s Content and personal information</strong></span>. Unless it receives Customer&rsquo;s prior written consent, Connect LLC: (a) will not access, process, or otherwise use individual Customer content other than as necessary to facilitate the Services or anonymized in aggregate form; and (b) will not intentionally grant to any third-party access to such content except as may disclosed in our Privacy Policy. Notwithstanding the foregoing, Connect LLC may disclose this content as required by applicable law or by proper legal or governmental authority. Connect LLC will give Customer prompt notice of any such legal or governmental demand and reasonably cooperate with Customer in any effort to seek a protective order or otherwise to contest such required disclosure, at Customer&rsquo;s expense.</p>
<p><span size="3">3.3&nbsp;</span><span size="3"><strong>Further Compliance.</strong></span> In using Connect LLC&rsquo;s Services, Application services or other services, Customer may be engaged with third parties. Customer hereby consents and expressly agrees to be bound by any and all privacy policies and terms of use/service implemented by any such third party. Furthermore, Customer shall comply with all such policies and terms, as well as all other local, state, and federal laws in accordance with these Terms.</p>
<p><span size="3">3.4&nbsp;</span><span size="3"><strong>Privacy Policy</strong></span>. Customer&rsquo;s privacy and security of their personal information is important to Connect LLC. We have provided details of our use of your personal information, our obligations with respect to that information, and your related rights in our Privacy Policy, which is incorporated into these Terms by this reference.</p>
<p>4. SAFETY AND GUIDELINES.</p>
<p>5.1 <strong>Safety</strong>. You agree to treat other users in a courteous and respectful manner, both on and off our Services and to be respectful when communicating with any of our customer care representatives or other employees. Though Connect LLC strives to encourage a respectful member experience, Connect LLC is not responsible for the conduct of any member on or off of the Services. You agree to use caution in all interactions with other Users, particularly if you decide to communicate off the Services or meet in person. You agree that you will not provide your financial information (for example, your credit card or bank account information), or wire or otherwise send money to other Users. YOU ARE SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER USERS. YOU UNDERSTAND THAT CONNECT LLC DOES NOT CONDUCT CRIMINAL BACKGROUND CHECKS ON ITS USERS OR OTHERWISE INQUIRE INTO THE BACKGROUND OF ITS USERS. CONNECT LLC MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OR COMPATIBILITY OF USERS. CONNECT LLC RESERVES THE RIGHT TO CONDUCT &ndash; AND YOU AUTHORIZE CONNECT LLC TO CONDUCT &ndash; ANY CRIMINAL BACKGROUND CHECK OR OTHER SCREENINGS (SUCH AS SEX OFFENDER REGISTER SEARCHES) AT ANY TIME USING AVAILABLE PUBLIC RECORDS OBTAINED BY IT OR WITH THE ASSISTANCE OF A CONSUMER REPORTING AGENCY, AND YOU AGREE THAT ANY CONTENT YOU PROVIDE MAY BE USED FOR THAT PURPOSE.</p>
<p>5.2 <strong>Guidelines.</strong> You agree not to engage in any of the following conduct both while using the Services and while engaging in activities with any nexus to the Services:</p>
<ul>
    <li>
        <p>Use the Services for any purpose that is illegal or prohibited by this Agreement.</p>
    </li>
    <li>
        <p>Use the Services for any harmful or nefarious purpose.</p>
    </li>
    <li>
        <p>Use of the Services in order to damage Connect LLC.</p>
    </li>
    <li>
        <p>Spam or solicitation of money or other items of value from another User, whether as a gift, loan, or other form of compensation, or otherwise defraud any User.</p>
    </li>
    <li>
        <p>Impersonate any person or entity or port any images of another person without his or her permission.</p>
    </li>
    <li>
        <p>Bully, &ldquo;stalk&rdquo;, intimidate, assault, harass, mistreat or defame, or otherwise mistreat any person.</p>
    </li>
    <li>
        <p>Post any content that violates or infringes anyone&rsquo;s rights, including rights of publicity, privacy, copyright, trademark or other intellectual property or contract right.&nbsp;</p>
    </li>
    <li>
        <p>Post any content that is hate speech, threatening, sexually explicit or pornographic; incites violence; or contains nudity or graphic or gratuitous violence.</p>
    </li>
    <li>
        <p>Post any content that promotes racism, bigotry, hatred or physical harm of any kind against any group or individual.</p>
    </li>
    <li>
        <p>Solicitation of passwords for any purpose, or personal identifying information for commercial or unlawful purposes from other users or disseminating another person&rsquo;s personal information without his or her permission.</p>
    </li>
    <li>
        <p>Use of another User&rsquo;s account, share an account with another User, or maintain more than one account.</p>
    </li>
    <li>
        <p>Misrepresent your identity, age, current or previous positions, qualifications, or affiliations with a person or entity.</p>
    </li>
    <li>
        <p>Create another account if we have already terminated your account unless you have our permission.</p>
    </li>
</ul>
<p>6. DATES TO SERVICES; SUPPORT.</p>
<p><span size="3">6.1&nbsp;</span><span size="3"><strong>Updates</strong></span>. Connect LLC may, from time to time, update or make changes to the features or functions of the Services. Connect LLC will make reasonable efforts to provide Customer with advance notice before removing any material feature or functionality of the Services, unless security, legal, or system performance considerations require an expedited change, in which case Connect LLC will provide Customer with notice as soon as reasonably possible.</p>
<p><span size="3">6.2&nbsp;</span><span size="3"><strong>Error Correction</strong></span><span size="3">. Connect LLC shall use commercially reasonable efforts to correct all Errors or to provide a reasonable workaround as soon as is possible using its reasonable efforts during Connect LLC&rsquo;s normal business hours. Customer shall provide such access, information, and support as Connect LLC may reasonably require in the process of resolving any error. This paragraph is Customer&rsquo;s sole and exclusive remedy for Errors. &ldquo;</span><span size="3"><strong>Error</strong></span>&rdquo; as used in this Section means any reproducible material failure of the Services to function in accordance with the Documentation.</p>
<p><span size="3">6.3&nbsp;</span><span size="3"><strong>Support Exclusions</strong></span>. Connect LLC has no obligation to correct any Errors or provide any other support to the extent such Errors or need for support was created in whole or in part by: (a) the acts, omissions, negligence or willful misconduct of Customer, including any unauthorized modifications of the Services or its operating environment; (b) any failure or defect of Customer&rsquo;s or a third party&rsquo;s equipment, software, facilities, third-party applications, or internet connectivity; (c) Customer&rsquo;s use of the Services other than in accordance with applicable Documentation provided to Customer; or (d) a Force Majeure Event.</p>
<p>7. OWNERSHIP.</p>
<p><span size="3">7.1&nbsp;</span><span size="3"><strong>Services Ownership</strong></span><span size="3">. Customer acknowledges that access to and use of the Services is licensed and not sold. Connect LLC, or its licensors, shall retain sole and exclusive ownership and all rights, title and interest in, including Intellectual Property Rights embodied or associated with, the Services, the Application, the Website, and any modifications or derivative works thereto. Without limiting the foregoing, the Application, Website, Services, Software, Documentation and all information and screens appearing on the Application or the Website (excluding the User content that is not aggregated and anonymized), including without limitation documents, site design, text, graphics, logos, images and icons, as well as the compilation and arrangement thereof, are the sole property of Connect LLC or its licensors, and are protected by copyright, work product and trademark laws. Except as otherwise required or limited by applicable law, any reproduction, distribution, modification, retransmission, or publication of any copyrighted material is strictly prohibited without the express written consent of Connect LLC and/or its licensors. Customer agrees that Connect LLC will have a perpetual right to use in any manner all suggestions, enhancement requests, feedback, and recommendations provided by Customer or Users relating to the Services (collectively, &ldquo;</span><span size="3"><strong>Feedback</strong></span>&rdquo;) without any obligation of compensation.</p>
<p>8. FEES; TAXES; PAYMENT.</p>
<p><span size="3">8.1&nbsp;</span><span size="3"><strong>Fees</strong></span><span size="3">. Connect LLC may offer products and services for purchase on the App or the Website (in either case, an &ldquo;</span><span size="3"><strong>In-App Purchase</strong></span><span size="3">&rdquo;). If you choose to make an In-App Purchase, you acknowledge and agree that additional terms, disclosed to you at the point of purchase, may apply, and that such additional terms are incorporated herein by reference. We may make In-App Purchases available through the following payment methods (&ldquo;</span><span size="3"><strong>Payment Method</strong></span><span size="3">&rdquo;): (a) making a purchase through a third-party platform such as the Apple App Store and Google Play Store (&ldquo;</span><span size="3"><strong>Third Party Store</strong></span><span size="3">&rdquo;), or (b) paying with your credit card, debit card, or PayPal account, or other third-party payment processor, which will be processed by a third-party processor. Once you have made an In-App Purchase, you authorize us to charge your chosen Payment Method. If payment is not received by us from your chosen Payment Method, you agree to promptly pay all amounts due upon demand by us.&nbsp;</span></p>
<p><span size="3">8.2&nbsp;</span><span size="3"><strong>Subscriptions and Auto-Renewal</strong></span><span size="3">. Connect LLC may offer some services as automatically renewing subscriptions, e.g., a one-week subscription, one-month subscription, or one-year subscription, (&ldquo;</span><span size="3"><strong>Premium Services</strong></span><span size="3">&rdquo;). IF YOU PURCHASE AN AUTOMATICALLY RENEWING SUBSCRIPTION, YOUR SUBSCRIPTION WILL RENEW AT THE END OF THE RELEVANT PERIOD, UNLESS YOU CANCEL, AT CONNECT LLC&rsquo;S THEN-CURRENT PRICE FOR SUCH SUBSCRIPTIONS. To avoid charges for a new subscription period, you must cancel, as described below, before the end of the then-current subscription period.&nbsp;</span>Deleting your account or deleting the application from your device does not cancel your subscription.&nbsp;You will be given notice of any changes in the pricing of the Premium Services to which you have subscribed and an opportunity to cancel. If Connect LLC changes these prices and you do not cancel your subscription, you agree that you will be charged at Connect LLC&rsquo;s then-current pricing for subscription.</p>
<p><span size="3">8.3.&nbsp;</span><span size="3"><strong>Cancelling Subscriptions</strong></span><span size="3">. If you purchased a subscription directly from Connect LLC, you may cancel or change your Payment Method via the payment settings option under your profile. If you purchased a subscription through a Third Party Store, such as the Apple App Store or the Google Play Store, you will need to access your account with that Third Party Store and follow instructions to change or cancel your subscription. If you cancel your subscription, you may use your subscription until the end of the period you last paid for, but (i) you will not (except as set forth in the subsection entitled &ldquo;Refunds&rdquo; below) be eligible for a prorated refund, (ii) your subscription will not be renewed when that period expires, and (iii) you will then no longer be able to use the Premium Services or In-App Purchases enabled by your subscription. If you sign up for a free trial and do not cancel, your trial may convert into a paid subscription and your Payment Method will be charged at the then-current price for such subscription. Once your free trial converts to a paid subscription, your paid subscription will continue to automatically renew at the end of each period, and your Payment Method will be charged, until you cancel. To avoid charges for a new subscription period, you must cancel before the end of the then-current subscription period or free trial period as described above.&nbsp;</span>Deleting your account or deleting the application from your device does not cancel your free trial.&nbsp;If you have signed up for a free trial on Connect LLC through the Apple Store or Google Play Store previously, you will not be eligible for another free trial and you will then be automatically signed up to a subscription and charged as described in this paragraph.</p>
<p><span size="3">8.4&nbsp;</span><span size="3"><strong>Payment Terms</strong></span><span size="3">. Customer agrees to promptly notify Connect LLC of any changes to its billing information. If Customer uses a credit card to make payments due under these Terms, Customer authorizes Connect LLC to automatically charge such credit card on a recurring basis during the Term for all applicable fees and taxes. If Customer is invoiced for fees and taxes, all amounts are payable in U.S. dollars net fifteen (15) days from the date of the invoice unless otherwise specified in the applicable Order.&nbsp;</span></p>
<p><span size="3">8.5&nbsp;</span><span size="3"><strong>Taxes</strong></span>. Customer shall pay or shall reimburse Connect LLC for all sales taxes, duties, and other taxes, however characterized by the taxing authority, based upon the subscription fees or other charges under these Terms or otherwise incurred on account of Customer&rsquo;s use of the Services, except for any taxes based upon Connect LLC&rsquo;s net income or gross receipts. If Customer is exempt from any applicable taxes, Customer will provide Connect LLC with a valid tax exemption certificate authorized by the appropriate taxing authority to evidence Customer&rsquo;s tax-exempt status. If Customer requires a purchase order or other similar documentation, such requirement will in no way affect or delay Customer&rsquo;s obligation to pay any amounts due hereunder, and Connect LLC expressly rejects any additional or different terms or conditions set forth on any Customer purchase order or similar documentation.</p>
<p><span size="3">8.6&nbsp;</span><span size="3"><strong>Refunds</strong></span>. Except as expressly set forth in these Terms, Connect LLC does not issue refunds for Services not used in the event of cancellation or discontinued use of the Services. If Customer terminates these Terms and any applicable order due to Connect LLC&rsquo;s uncured breach, Customer will be entitled to a prorated refund of any prepaid, unused fees for the Services.</p>
<p><span size="3">8.7&nbsp;</span><span size="3"><strong>Payment Disputes</strong></span>. Customer must notify Connect LLC in writing of any disputes regarding invoiced or charged amounts within fifteen (15) days after Customer&rsquo;s receipt of the applicable invoice or credit card charge. Customer&rsquo;s Notice must include an explanation detailing the basis of Customer&rsquo;s dispute of the invoiced or charged amount. The Parties will seek to resolve any properly disputed amount only as permitted by these Terms. If only a portion of an invoice or charge is disputed, Customer will pay the non-disputed portion as required hereunder. Connect LLC may suspend access to the Services if Customer improperly or unreasonably disputes or fails to pay amounts owed when due. If the Parties are unable to come to an agreement with respect to disputed amounts, either Party may seek appropriate legal or equitable remedies, all of which are reserved.</p>
<p>9. REPRESENTATIONS AND WARRANTIES; DISCLAIMER.</p>
<p><span size="3">9.1&nbsp;</span><span size="3"><strong>Connect LLC&rsquo;s General Representation and Warranty</strong></span>. Connect LLC represents and warrants that: (a) it is a corporation authorized to do business pursuant to applicable law; and (b) it has the full right and authority to enter into, execute, and perform its obligations under these Terms; and (c) it will comply with all laws, treaties and regulations applicable to its provision of the Services.</p>
<p><span size="3">9.2&nbsp;</span><span size="3"><strong>Connect LLC&rsquo;s Limited Warranty for Services</strong></span>. If Customer has paid fees under these Terms for the Services, Connect LLC represents and warrants that the Services will operate substantially as described in the Documentation, but provides no representation or warranty with respect to a Customer&rsquo;s rate of success in connecting with other Users. Customer must notify Connect LLC in writing of any alleged failure by Connect LLC to comply with this warranty within thirty (30) days of such failure. Upon receipt of such notice, Connect LLC will either: (a) use commercially reasonable efforts to cure or correct the failure, or (b) terminate the applicable Order and issue a prorated refund for the terminated portion of the Services. This Section 9.2 sets forth Customer&rsquo;s exclusive rights and remedies and Connect LLC&rsquo;s sole liability for breach of the limited warranty for Services specified herein.</p>
<p><span size="3">9.3&nbsp;</span><span size="3"><strong>Customer Representations and Warranties</strong></span>. Customer represents and warrants that: (a) it is an individual authorized to partake in the Services pursuant to applicable law; (b) it has the full right and authority to enter into, execute, and perform its obligations under these Terms; (c) it has all rights, permissions, and consents necessary (i) to submit all necessary Customer content and personal information to the Services, (ii) to grant Connect LLC the limited rights to process Customer content and personal information as set forth in these Terms, and (iii) for any transfer or disclosure of Customer content and personal information among or by Users; and (d) he or she will comply with all laws and regulations applicable to its use of the Services.</p>
<p><span size="3">9.4&nbsp;</span><span size="3"><strong>WARRANTY DISCLAIMER</strong></span>. EXCEPT FOR THE WARRANTIES SET FORTH ABOVE IN THIS SECTION 9, CONNECT LLC MAKES NO REPRESENTATIONS OR WARRANTIES WITH RESPECT TO THE SERVICE, THE APPLICATION, THE WEBSITE OR ANY INFORMATION OR MATERIALS RELATED THERETO OR MADE AVAILABLE THEREFROM, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT, OR ANY IMPLIED WARRANTY ARISING FROM STATUTE, COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, CONNECT LLC DOES NOT REPRESENT OR WARRANT THAT (A) THE SERVICE OR APPLICATION WILL PERFORM WITHOUT INTERRUPTION, DOWNTIME, OR ERROR; (B) THE SERVICE OR APPLICATION ARE SECURE FROM HACKING OR OTHER UNAUTHORIZED INTRUSION OR THAT CUSTOMER CONTENT WILL REMAIN PRIVATE OR SECURE.</p>
<p>10. INDEMNIFICATION.</p>
<p><span size="3">10.1&nbsp;</span><span size="3"><strong>Indemnification by Customer</strong></span><span size="3">. Customer shall defend, at its expense, Connect LLC and its officers, directors, employees, and agents (&ldquo;</span><span size="3"><strong>Connect LLC Indemnified Parties</strong></span>&rdquo;) from and against any claims, demands, proceedings, investigations, or suits brought by a third party arising out of: (a) the Customer&rsquo;s noncompliance of these Terms; or (b) Customer&rsquo;s use of the Application or the Website in violation of these Terms or applicable law. Customer shall indemnify and hold harmless Connect LLC Indemnified Parties from and against any damages, reasonable attorney&rsquo;s fees, and costs arising out of or resulting from a claim that Customer is obligated to defend pursuant to this Section 10.1 and finally awarded against Connect LLC or agreed to be paid by Connect LLC in a written settlement approved by Customer in writing.</p>
<p><span size="3">10.2&nbsp;</span><span size="3"><strong>Conditions on Indemnification</strong></span>. The indemnifying Party&rsquo;s obligations under this Section 10 are contingent on Connect LLC: (a) promptly providing written Notice of the claim to the indemnifying Party (provided that the failure of a Party entitled to indemnification hereunder to give Notice as provided herein shall not relieve the indemnifying Party of its obligations under this Section 10 except to the extent that the indemnifying Party is actually prejudiced by such failure to give Notice); (b) giving the indemnifying Party control of the defense and settlement of the claim (provided that any settlement unconditionally releases Connect LLC of all liability and does not make any admissions on behalf of Connect LLC or include payment of any amounts by any Connect LLC Indemnified Party); and (c) providing the indemnifying Party, at the indemnifying Party&rsquo;s expense, all reasonable assistance in connection with such claim. Connect LLC may participate in the defense of the claim at its sole cost and expense.</p>
<p>11. LIMITATIONS OF LIABILITY.</p>
<p><span size="3">11.1&nbsp;</span><span size="3"><strong>EXCLUSION OF CONSEQUENTIAL DAMAGES</strong></span>. IN NO EVENT WILL CONNECT LLC HAVE ANY LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS FOR ANY LOST PROFITS, LOST REVENUES, LOSS OF GOODWILL, OR FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, WHETHER AN ACTION IS IN CONTRACT OR TORT AND REGARDLESS OF THE THEORY OF LIABILITY, EVEN IF CONNECT LLC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR IF CONNECT LLC&rsquo;S REMEDY OTHERWISE FAILS OF ITS ESSENTIAL PURPOSE.</p>
<p><span size="3">11.2&nbsp;</span><span size="3"><strong>LIMITATION OF LIABILITY</strong></span>. IN NO EVENT SHALL THE AGGREGATE LIABILITY OF CONNECT LLC ARISING OUT OF OR RELATED TO THESE TERMS EXCEED THE TOTAL AMOUNT PAID BY CUSTOMER HEREUNDER FOR THE SERVICE GIVING RISE TO THE LIABILITY IN THE TWELVE (12) MONTHS PRECEDING THE FIRST INCIDENT FROM WHICH THE LIABILITY AROSE. THE FOREGOING LIMITATION WILL APPLY WHETHER AN ACTION IS IN CONTRACT OR TORT AND REGARDLESS OF THE THEORY OF LIABILITY BUT WILL NOT LIMIT CUSTOMER&rsquo;S PAYMENT OBLIGATIONS AS SET FORTH HEREIN.</p>
<p>11.2.1 THE LIMITATIONS OF LIABILITY SET FORTH IN THIS SECTION DO NOT APPLY TO LIABILITY THAT MAY NOT BE LIMITED OR EXCLUDED BY APPLICABLE LAW.</p>
<p>11.2.2 EACH PROVISION OF THESE TERMS THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES REPRESENTS AN AGREED UPON ALLOCATION OF THE RISKS OF THESE TERMS BETWEEN THE PARTIES. THE FEES FOR THE SERVICE REFLECT THIS ALLOCATION OF RISK.</p>
<p>12. DMCA POLICY</p>
<p><span size="3">12.1&nbsp;</span><span size="3"><strong>Compliance with DMCA</strong></span><span size="3">. Connect LLC respects the intellectual property rights of others and expects its users to do the same. In accordance with the Digital Millennium Copyright Act of 1998, the text of which may be found on the U.S. Copyright Office website at http://www.copyright.gov/legislation/dmca.pdf, Connect LLC will respond expeditiously to claims of copyright infringement committed using the Application, the Website, or the Services if such claims are reported to Connect LLC&rsquo;s Designated Copyright Agent identified in the sample notice below.&nbsp;</span></p>
<p><span size="3">12.2&nbsp;</span><span size="3"><strong>Infringement Policy</strong></span><span size="3">. If you are a copyright owner, authorized to act on behalf of one, or authorized to act under any exclusive right under copyright, please report alleged copyright infringements taking place on or through the Site by completing the following DMCA Notice of Alleged Infringement and delivering it to Connect LLC&rsquo;s Designated Copyright Agent. Upon receipt of DMCA Notice as described below, Connect LLC will take whatever action, in its sole discretion, it deems appropriate, including removal of the challenged content from the Website.&nbsp;</span></p>
<p><span size="3">12.3&nbsp;</span><span size="3"><strong>DMCA Notice of Alleged Infringement</strong></span><span size="3">. (&ldquo;</span><span size="3"><strong>DMCA Notice</strong></span>&rdquo;) We reserve the right to not act upon any notice that does not comply with the requirements listed below. In order to be actionable, any DMCA Notice must:</p>
<ul>
    <li>
        <p>Identify the copyrighted work that you claim has been infringed, or - if multiple copyrighted works are covered by this DMCA Notice - you may provide a representative list of the copyrighted works that you claim have been infringed.&nbsp;</p>
    </li>
    <li>
        <p>Identify the material or link you claim is infringing (or the subject of infringing activity) and to which access is to be disabled, including at a minimum, if applicable, the URL of the link shown on the exact location where such material may be found.&nbsp;</p>
    </li>
    <li>
        <p>Provide your company affiliation (if applicable), mailing address, telephone number, and, if available, email address.&nbsp;</p>
    </li>
    <li>
        <p>Include both of the following statements in the body of the Notice:&nbsp;</p>
        <ul>
            <li>
                <p>&ldquo;I hereby state that I have a good faith belief that the disputed use of the copyrighted material is not authorized by the copyright owner, its agent, or the law (e.g., as a fair use).&rdquo;&nbsp;</p>
            </li>
            <li>
                <p>&ldquo;I hereby state that the information in this DMCA Notice is accurate and, under penalty of perjury, that I am the owner, or authorized to act on behalf of, the owner, of the copyright or of an exclusive right under the copyright that is allegedly infringed.&rdquo;&nbsp;</p>
            </li>
        </ul>
    </li>
    <li>
        <p><span size="3">Provide your full legal name and your electronic or physical signature. Deliver this notice, with all items completed, to Connect LLC&rsquo;s Designated Copyright Agent: [</span><em>Insert email AND mailing address]</em></p>
    </li>
</ul>
<p>13. DISPUTE RESOLUTION</p>
<p><span size="3">13.1 U.S.&nbsp;</span><span size="3"><strong>Dispute Resolution</strong></span>. You and Connect LLC agree that any dispute, claim or controversy arising out of or relating in any way to Connect LLC, these Terms and this agreement to arbitrate, will be determined by binding arbitration or in small claims court in the United States. You agree that, by agreeing to these Terms, the U.S. Federal Arbitration Act governs the interpretation and enforcement of this provision, and that you and Connect LLC are each waiving the right to a trial by jury or to participate in a class action. This arbitration provision will survive termination of these Terms and the termination of your Connect LLC account.</p>
<p><span size="3">13.2&nbsp;</span><span size="3"><strong>Procedure on Dispute</strong></span><span size="3">. If you elect to seek arbitration or file a small claim court action, you must first send to Connect LLC, by certified mail, a written Notice of your claim (&ldquo;</span><span size="3"><strong>Notice</strong></span><span size="3">&rdquo;). The Notice to Connect LLC must be addressed to: Connect LLC, 1219 6</span><sup>th</sup><span size="3">&nbsp;Ave N, Apt 101, Seattle, Washington 98109-3429, USA (&ldquo;</span><span size="3"><strong>Connect Notice Address</strong></span><span size="3">&rdquo;). If Connect LLC initiates arbitration, it will send a written Notice to the email address used for your account &ldquo;</span><span size="3"><strong>Customer Notice Address</strong></span><span size="3">&rdquo; and together with Connect Notice Address, a &ldquo;</span><span size="3"><strong>Notice Address</strong></span>&rdquo;). A Notice, whether sent by you or by Connect LLC, must: (1) describe the nature and basis of the claim or dispute; and (2) set forth the specific relief sought. If Connect LLC and you do not reach an agreement to resolve the claim within 60 days after the Notice is received, you or Connect LLC may commence an arbitration proceeding or file a claim in small claims court.</p>
<p><span size="3">13.3&nbsp;</span><span size="3"><strong>Governing Rules</strong></span>. The arbitration will be governed by the Commercial Arbitration Rules (AAA Rules) of the American Arbitration Association (AAA), as modified by these Terms, and will be administered by the AAA. Unless Connect LLC and you agree otherwise, any arbitration hearings will take place in King County in the state of Washington, U.S.A. The arbitrator&rsquo;s award will be final and binding on all parties, except: (1) for judicial review expressly permitted by law; or (2) if the arbitrator&rsquo;s award includes an award of injunctive relief against a party, in which case that party will have the right to seek judicial review of the injunctive relief in a court of competent jurisdiction that will not be bound by the arbitrator&rsquo;s application or conclusions of law. Arbitration will occur before one (1) arbitrator selected under the AAA rules. THIS PROVISION DOES NOT APPLY TO INJUNCIVE RELIEF SOUGHT BY CONNECT LLC.</p>
<p>13.4. YOU AND CONNECT LLC AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and Connect LLC agree otherwise, the arbitrator may not consolidate more than one person&rsquo;s claims with your claims and may not otherwise preside over any form of a representative or class proceeding. If this specific provision is found to be unenforceable, then the entirety of this arbitration provision will be null and void.</p>
<p>14. GENERAL.</p>
<p><span size="3">14.1&nbsp;</span><span size="3"><strong>Force Majeure Event</strong></span>. Neither Party shall be liable to the other Party for failure or delay in performing its obligations under these Terms when such failure or delay is due to a Force Majeure Event, provided that the Nonperforming Party shall give prompt written notice thereof to the Performing Party and shall use commercially reasonable efforts to resume performance as quickly as possible.</p>
<p><span size="3">14.2&nbsp;</span><span size="3"><strong>Assignment</strong></span>. Except as expressly set forth herein, neither Party will assign, transfer or delegate its rights or obligations under these Terms (in whole or in part) without the other Party&rsquo;s prior written consent. Notwithstanding the foregoing, Connect LLC may assign these Terms or any Order or other agreement between the Parties in whole to an affiliate or pursuant to a transfer of all or substantially all of such Connect LLC&rsquo;s business and assets, whether by merger, sale of assets, sale of stock, or otherwise. Any attempted assignment, transfer or delegation in violation of the foregoing shall be null and void.</p>
<p><span size="3">14.3&nbsp;</span><span size="3"><strong>Third Parties</strong></span>. Connect LLC may provide references, frames or hyperlinks to internet web sites maintained by third parties. Connect LLC does not warrant that it has reviewed such third-party websites and makes no claims, representations or warranties regarding such third-party websites or the contents of the same. Connect LLC is not responsible for, nor does it endorse or recommend, any products or services provided by such third parties through such third-party websites or by any other means.</p>
<p><span size="3">14.4&nbsp;</span><span size="3"><strong>U.S. Government Restricted Rights; Export</strong></span>. Any software provided hereunder is a &ldquo;commercial item,&rdquo; as defined at 48 C.F.R. &sect; 2.101 (OCT 1995), and more specifically is &ldquo;commercial computer software&rdquo; and &ldquo;commercial computer software documentation,&rdquo; as such terms are used in 48 C.F.R. &sect; 12.212 (SEPT 1995). Consistent with 48 C.F.R. &sect; 12.212 and 48 C.F.R. &sect;&sect; 227.7202-1 through 227.7202-4 (JUNE 1995), such software is provided to U.S. Government End Users only as a commercial end item and with only those rights as are granted to all other end users pursuant to the terms and conditions herein. If Customer exports any of the software, it must comply fully with all relevant export laws and regulations to ensure that the software is not exported, directly or indirectly, in violation of applicable export control laws. Customer shall not knowingly, directly or indirectly, without prior written consent, general or specific license, if required, of the Office of Export Administration of the U.S. Department of Commerce, export or transmit any of the software to any country to which such transmission is restricted by applicable regulations or statutes.</p>
<p><span size="3">14.5&nbsp;</span><span size="3"><strong>Notices</strong></span>. Any Notice required or permitted by these Terms shall be delivered in accordance with the requirements for Notice set forth in Section 13.2 (Procedure on Dispute).</p>
<p><span size="3">14.6&nbsp;</span><span size="3"><strong>Relationship; Third Party Beneficiaries</strong></span>. These Terms do not create any partnership, franchise, joint venture, agency, or fiduciary or employment relationship. Neither Party may bind the other Party or act in a manner which expresses or implies a relationship other than that of independent contractor.</p>
<p><span size="3">14.7&nbsp;</span><span size="3"><strong>Invalidity; Non-Waiver</strong></span>. If any term of these Terms is held to be invalid, illegal or unenforceable, the validity, legality and enforceability of the remaining provisions shall not be affected or impaired. Any express waiver or failure to exercise promptly any right under these Terms will not create a continuing waiver or any expectation of non-enforcement.</p>
<p><span size="3">14.8&nbsp;</span><span size="3"><strong>Governing Law; Dispute Resolution</strong></span><span size="3">. These Terms shall be governed by and construed under the laws of the State of Washington without regard to its conflicts of laws. Any controversy, dispute or claim arising out of or in connection with these Terms is subject to the dispute resolution process detailed in Section 13.&nbsp;</span></p>
<p><span size="3">14.9&nbsp;</span><span size="3"><strong>Conflict</strong></span>. In the event of a conflict between the terms and conditions of these Terms and those of an Order, purchase order, or any subsequent agreement between the Parties, the terms and conditions of these Terms will control, unless specifically stated otherwise in the Order, purchase order, or subsequent agreement.</p>
<p><span size="3">14.10&nbsp;</span><span size="3"><strong>Changes to These Terms</strong></span>. We may make changes to these Terms from time to time. If we do make changes, we will post the amended Terms on the Site and update the &ldquo;Last Updated&rdquo; date above. If we make a material change to these Terms, we will make reasonable efforts to notify you in advance by posting a notice on the Website, or via Customer&rsquo;s dashboard in the Application, or via email to Administrator email addresses on file with us. Unless we indicate otherwise, the amended Terms will be effective once posted and your continued access to and use of the Services after such time will confirm your acceptance of the Terms as modified. If you do not agree to the modified Terms, you must stop using our Services.</p>
<p><span size="3">14.11&nbsp;</span><span size="3"><strong>Entire Agreement</strong></span><span size="3">. These Terms constitute the entire agreement between Connect LLC and Customer regarding Customer&rsquo;s use of the Services, the Application and the Website and supersedes all prior and contemporaneous agreements, proposals or representations, written or oral, concerning its subject matter.&nbsp;</span></p>',
                'policies_status' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'About Us',
                'slug' => 'about-us',
                'content' => 'Welcome to Cennec, where genuine connections begin! Our mission is simple: to help you find meaningful relationships in a fun, safe, and engaging way. We believe in the power of real connections, which is why our app focuses on quality over quantity. With advanced matching algorithms, personalized profiles, and a user-friendly interface, Cennec is designed to bring people together who share your values and interests. Whether you’re looking for a serious relationship or a fun date, our platform caters to all kinds of connections. Join our community today and discover a new way to meet people who truly matter. Your next great relationship is just a swipe away!',
                'policies_status' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Community Guidlines',
                'slug' => 'community-guidlines',
                'content' => 'Respect Everyone: Treat all members with kindness and respect. Harassment, discrimination, or hate speech of any kind is not tolerated.
            Be Honest: Provide accurate and truthful information in your profile. Misrepresentation undermines trust and the integrity of our community.
            Privacy Matters: Respect the privacy of others. Do not share personal information or photos of other users without their consent.
            No Spam or Scams: Avoid sending unsolicited messages, promotional content, or engaging in fraudulent activities. Report any suspicious behavior immediately.
            Appropriate Content: Share content that is appropriate for all audiences. Nudity, explicit content, or inappropriate language is prohibited.
            Safe Interactions: Arrange meetings in public places and always prioritize your safety. Report any concerning behavior to our support team.
            Constructive Communication: Engage in conversations that are positive and constructive. Negative or aggressive interactions are discouraged.
            Follow the Law: Ensure your actions on the platform comply with all relevant laws and regulations',
                'policies_status' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
